5-module/1-task
js-tasks-ru/jsbasic-20240708-2_yaroslavzhoock pull request #16
Opened 2024-07-27 17:03 UTC by zhoock

2024-07-27 17:03 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-07-28 15:33 UTC, koalex requested changes
Исправить **5-1**

2024-07-28 15:33 UTC, koalex commented on 5-module/1-task/task.test.js
Тесты нельзя трогать

2024-07-28 15:33 UTC, koalex commented on 5-module/1-task/index.html
> +    button.onclick = hideSelf;
Это тоже нельзя исправлять

2024-07-28 21:46 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-07-29 04:20 UTC, koalex approved these changes

2024-07-29 04:20 UTC, merged