5-module/2-task
js-tasks-ru/jsbasic-20240708-2_yaroslavzhoock pull request #17
Opened 2024-07-29 10:56 UTC by zhoock

2024-07-29 10:57 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-07-30 05:10 UTC, koalex requested changes
Замечание **5-2**

2024-07-30 05:10 UTC, koalex commented on 5-module/2-task/index.js
> +  text.previousElementSibling.onclick = _ => text.hidden = !text.hidden;
На занятии говорил, что обращение напрямую по `id` - это плохо и делать так не нужно. Исправить на `document.querySelector('#text')`

2024-07-30 07:37 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-07-30 08:12 UTC, koalex approved these changes

2024-07-30 08:12 UTC, merged